trigger:
- master 

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
   script: |
     brew install terraform
     brew install accurics

     accurics init
     accurics plan -fail